// Generated by CoA-Custom/scripts/gen_coa_racials.py from coa_racials.py: do not edit by hand.
// The racials of every non-vanilla race (12 and up): an active and a passive spell (spell_dbc / client Spell.dbc).
// They replace the racials these races had; the vanilla races 1-11 keep theirs.
#ifndef COA_CUSTOM_RACIALS_H
#define COA_CUSTOM_RACIALS_H

#include "Define.h"
#include <array>

struct CoaCustomRacial
{
    uint8 RaceId;
    uint32 ActiveSpell;
    uint32 PassiveSpell;
};

inline constexpr std::array<CoaCustomRacial, 42> CoaCustomRacials =
{{
    {12, 14000121, 14000122},
    {13, 14000131, 14000132},
    {14, 14000141, 14000142},
    {15, 14000151, 14000152},
    {16, 14000161, 14000162},
    {17, 14000171, 14000172},
    {18, 14000181, 14000182},
    {20, 14000201, 14000202},
    {21, 14000211, 14000212},
    {22, 14000221, 14000222},
    {23, 14000231, 14000232},
    {24, 14000241, 14000242},
    {25, 14000251, 14000252},
    {26, 14000261, 14000262},
    {28, 14000281, 14000282},
    {29, 14000291, 14000292},
    {30, 14000301, 14000302},
    {31, 14000311, 14000312},
    {32, 14000321, 14000322},
    {47, 14000471, 14000472},
    {48, 14000481, 14000482},
    {49, 14000491, 14000492},
    {50, 14000501, 14000502},
    {51, 14000511, 14000512},
    {53, 14000531, 14000532},
    {54, 14000541, 14000542},
    {55, 14000551, 14000552},
    {56, 14000561, 14000562},
    {57, 14000571, 14000572},
    {58, 14000581, 14000582},
    {59, 14000591, 14000592},
    {60, 14000601, 14000602},
    {61, 14000611, 14000612},
    {62, 14000621, 14000622},
    {63, 14000631, 14000632},
    {66, 14000661, 14000662},
    {67, 14000671, 14000672},
    {68, 14000681, 14000682},
    {69, 14000691, 14000692},
    {70, 14000701, 14000702},
    {71, 14000711, 14000712},
    {74, 14000741, 14000742},
}};

inline CoaCustomRacial const* GetCoaCustomRacial(uint8 race)
{
    for (CoaCustomRacial const& racial : CoaCustomRacials)
        if (racial.RaceId == race)
            return &racial;
    return nullptr;
}

#endif
