# CoA Custom 1.5: racials of every non-vanilla race (12 and up). Each race gets an active and a passive racial, made by
# copying a Blizzard racial (template: its mechanics and numbers) under a new id, name, lore text and icon. They
# replace the racials these races had (the vanilla races 1-11 keep theirs). Used by gen_coa_racials.py.
#
#   race: (active, passive)    with   (name, template spell, icon, lore line)
# Templates: 20549 War Stomp, 26297 Berserking, 20594 Stoneform, 58984 Shadowmeld, 20589 Escape Artist,
# 33697 Blood Fury, 28730 Arcane Torrent, 28880 Gift of the Naaru, 7744 Will of the Forsaken, 59752 Every Man for
# Himself, 20573 Hardiness, 20550 Endurance, 20591 Expansive Mind, 20598 The Human Spirit, 20555 Regeneration,
# 28878 Heroic Presence, 20582 Quickness, 20551/20579/20592/20596 Nature/Shadow/Arcane/Frost Resistance, 58985 Perception
RACIALS = {
    12: (('Embrace of the Loa', 28880, 'ability_racial_embracetheloa',
          'The Zandalari call on their loa, as every Witch Doctor of the empire learns to.'),
         ('Pterrordax Blood', 20555, 'ability_racial_pterrordaxswoop',
          'The blood of Zandalar heals what the jungle breaks.')),
    13: (('Darkflight', 20589, 'ability_worgen_darkflight',
          'The curse of the worgen frees those who embrace the beast, as Rangers and Reapers know.'),
         ('Viciousness', 28878, 'ability_racial_viciousness',
          'Gilneas hunts with the instincts of the wolf.')),
    14: (('Quel\'dorei Torrent', 28730, 'ability_racial_arcaneaffinity',
          'The High Elves still draw on the Sunwell\'s legacy, the first lesson of every Starcaller.'),
         ('Arcane Affinity', 20591, 'ability_racial_cantrips',
          'Silvermoon\'s exiles keep their sharp minds.')),
    15: (('Harpoon Charge', 20549, 'inv_misc_head_tuskarr',
          'Tuskarr hunters bring down their prey in one charge.'),
         ('Rime of the Ancient Mariner', 20596, 'ability_racial_rimeoftheancientmariner',
          'Born on the frozen shores of Northrend.')),
    16: (('Haymaker', 20549, 'ability_racial_haymaker',
          'Kul Tiran sailors settle things with their fists, a habit Barbarians admire.'),
         ('Brush It Off', 20550, 'ability_racial_brushitoff',
          'A Kul Tiran shrugs off what would drop anyone else.')),
    17: (('Thunderhoof', 20549, 'ability_racial_bullrush',
          'The Taunka shake the tundra like their southern cousins.'),
         ('Hardened by Northrend', 20596, 'spell_frost_wizardmark',
          'Generations of ice and wind.')),
    18: (('Fury of the Val\'kyr', 33697, 'inv_misc_head_vrykul',
          'The Vrykul fight with the rage of their titan forebears.'),
         ('Titan Blood', 20550, 'ability_racial_avatar',
          'Giants among men.')),
    20: (('Quaking Palm', 20549, 'ability_monk_paralysis',
          'Pandaren masters strike the nerve points, as their monks have for ages.'),
         ('Inner Peace', 20598, '_monkspecialattack_dodgepandaren',
          'A calm spirit recovers faster.')),
    21: (('Tidal Surge', 20589, 'spell_frost_summonwaterelemental',
          'The Naga slip from any hold like the tide.'),
         ('Serpent Scales', 20551, 'achievement_boss_elitenagamale',
          'Hardened scales from the depths of Nazjatar.')),
    22: (('Shattered Light', 28880, 'spell_holy_holyprotection',
          'The Broken still hold a spark of the Naaru\'s light, as their Sun Clerics remember.'),
         ('Exile\'s Resolve', 20579, 'spell_shadow_antishadow',
          'The fel could not break them fully.')),
    23: (('Fel Rage', 33697, 'spell_shadow_demonform',
          'Fel blood burns in their veins, a fire every Felsworn knows.'),
         ('Demonic Endurance', 20573, 'spell_shadow_ritualofsacrifice',
          'Fel-forged bodies shrug off blows that stun others.')),
    24: (('Headhunter\'s Frenzy', 26297, 'ability_racial_bloodrage',
          'The Amani fight in a blood frenzy.'),
         ('Jungle Stalker', 20582, 'ability_racial_shadowmeld',
          'Forest Trolls vanish among the trees.')),
    25: (('Frostmane Frenzy', 26297, 'spell_frost_frostward',
          'The trolls of the frozen north fight hot-blooded.'),
         ('Winter\'s Blood', 20596, 'ability_racial_rimeoftheancientmariner',
          'Born in the snows of Zul\'Drak.')),
    26: (('Bone Shield', 7744, 'ability_racial_skeletonpinkie',
          'No mind left to frighten, as every Necromancer intends.'),
         ('Unliving', 20579, 'spell_shadow_raisedead',
          'Death holds no more terror.')),
    28: (('Blood of the Gods', 26297, 'ability_racial_bloodrage',
          'The Drakkari drink the blood of their gods, a rite their Witch Doctors kept.'),
         ('Drakkari Regeneration', 20555, 'ability_racial_wardoftheloa',
          'Troll flesh mends itself.')),
    30: (('Mrgglrrgl!', 20589, 'inv_misc_head_murloc_01',
          'Nothing holds a slippery murloc for long.'),
         ('Amphibious', 20582, 'ability_racial_childofthesea',
          'Quick and hard to catch.')),
    32: (('Survivor\'s Will', 59752, 'achievement_character_human_male',
          'Lean, hungry and hard to keep down.'),
         ('Light Step', 20582, 'ability_rogue_sprint',
          'A thin frame dodges blows.')),
    47: (('Pack Howl', 33697, 'ability_racial_runningwild',
          'The alpha leads the pack into battle.'),
         ('Alpha Instinct', 58985, 'ability_racial_twoforms',
          'Nothing escapes the alpha\'s senses.')),
    48: (('Fireblood', 20594, 'ability_racial_fireblood',
          'The Dark Iron burn away what ails them, as their Pyromancers taught.'),
         ('Forged in Flames', 20573, 'ability_racial_foregedinflames',
          'Shadowforge steel and stubborn skulls.')),
    49: (('Ancestral Call', 33697, 'ability_racial_ancestralcall',
          'The Mag\'har call on the spirits of Draenor, as their Primalists do.'),
         ('Open Skies', 28878, 'ability_racial_openskies',
          'Untainted by the fel, their strikes fly true.')),
    50: (('Ursine Fury', 26297, 'ability_racial_bearform',
          'The Furbolg fight with the strength of the bear.'),
         ('Thick Fur', 20551, 'inv_cape_special_furbolg_d_01',
          'Children of the wild, at home in nature.')),
    51: (('Gnomish Defiance', 7744, 'spell_shadow_raisedead',
          'Death did not dull a gnome\'s stubborn mind, the first rule of any undead Tinker.'),
         ('Necrotic Intellect', 20591, 'ability_racial_betterlivingthroughchemistry',
          'Brilliance outlives the body.')),
    53: (('Ogre Slam', 20549, 'inv_ogrepet_blue',
          'One slam is usually enough.'),
         ('Two Heads Are Better', 20550, 'ability_racial_bloodrage',
          'Ogres are built to last.')),
    54: (('Wing Buffet', 20549, 'inv_misc_head_dragon_bronze',
          'Dracthyr scatter their foes with a beat of their wings, as their Chronomancers favor.'),
         ('Draconic Mind', 20591, 'inv_misc_head_dragon_01',
          'The aspects\' knowledge runs in their blood.')),
    55: (('Fel Torrent', 28730, 'achievement_boss_argus_maleeredar',
          'The Eredar unleash a torrent of fel, the gift every Felsworn craves.'),
         ('Man\'ari Mind', 20591, 'spell_shadow_demonicpact',
          'Ancient Argus minds, sharp as ever.')),
    56: (('Wing Gust', 20589, 'inv_feather_04',
          'Harpies take to the air to escape any snare.'),
         ('Swift Talons', 20582, 'ability_hunter_pet_raptor',
          'Hard to catch, quick to strike.')),
    57: (('Rocket Jump', 20589, 'ability_racial_rocketjump',
          'Every goblin carries a rocket for emergencies, a Tinker\'s favorite.'),
         ('Time is Money', 28878, 'ability_racial_timeismoney',
          'A goblin never wastes a swing.')),
    59: (('Spatial Rift', 58984, 'ability_racial_spatialrift',
          'Void Elves slip between the shadows, as their Cultists learned from the Void.'),
         ('Entropic Embrace', 20579, 'ability_racial_entropicembrace',
          'The Void protects its own.')),
    60: (('Spectral Sight', 58985, 'ability_demonhunter_spectralsight',
          'Illidari eyes see what hides.'),
         ('Demon Hunter\'s Resolve', 20573, 'ability_demonhunter_illidansgrasp',
          'Trained by Illidan to endure.')),
    61: (('Mana Break', 28730, 'achievement_boss_illidan',
          'The Illidari tear the magic from their foes.'),
         ('Demonbane', 20579, 'ability_racial_demonbane',
          'Sworn enemies of the Legion.')),
    62: (('Light\'s Reckoning', 28880, 'ability_racial_finalverdict',
          'The Lightforged carry the Naaru\'s light, as their Templars and Sun Clerics do.'),
         ('Forge of Light', 20598, 'ability_racial_forgeoflight',
          'The Light renews them.')),
    63: (('Arcane Pulse', 28730, 'ability_mage_arcanebarrage_nightborne',
          'The Nightborne master the arcane of Suramar, a Starcaller\'s dream.'),
         ('Ancient History', 20591, 'achievement_alliedrace_nightborne',
          'Ten thousand years of study.')),
    66: (('Bull Rush', 20549, 'ability_racial_bullrush',
          'Highmountain charge like the great moose.'),
         ('Mountaineer', 20550, 'ability_racial_mountaineer',
          'Raised on the peaks of Highmountain.')),
    67: (('Combat Analysis', 26297, 'ability_racial_combatanalysis',
          'Mechagnome processors read the fight, a Tinker\'s dream.'),
         ('Re-Origination', 20582, 'ability_racial_hyperorganiclightoriginator',
          'Optimized servos react faster.')),
    68: (('Azerite Surge', 20594, 'ability_earthenfury_giftofearth',
          'The Earthen are made of living stone, as their Runemasters remember.'),
         ('Titan-Forged', 20573, 'ability_earthen_pillar',
          'Stone does not stagger.')),
    70: (('Rootkin Mending', 28880, 'spell_nature_healingtouch',
          'The Haranir draw life from the roots of the world, as their Primalists do.'),
         ('Barkskin Hide', 20551, 'spell_nature_stoneclawtotem',
          'Bark and leaf protect them.')),
    74: (('Bag of Tricks', 20589, 'ability_racial_makecamp',
          'A Vulpera always has something in the bag.'),
         ('Nose for Trouble', 20582, 'ability_racial_returntocamp',
          'Desert scavengers dodge danger.')),
}
# both factions of the same people share their racials
for twin, base in ((29, 20), (31, 30), (58, 54), (69, 68), (71, 70)):
    RACIALS[twin] = RACIALS[base]

SPELL_BASE = 14000000          # new spell ids: SPELL_BASE + race * 10 + 1 (active), + 2 (passive)


def spell_ids(race):
    return SPELL_BASE + race * 10 + 1, SPELL_BASE + race * 10 + 2
