# CoA Custom 1.5: racials of every non-vanilla race (12 and up). Each race has 4 racials: 1 active + 3 passives, or
# 2 actives + 2 passives. Each one copies a Blizzard racial (the template: its mechanics and numbers) under a new id,
# name, lore line and icon. They replace the racials these races had (the vanilla races 1-11 keep theirs).
# Used by gen_coa_racials.py.
#
#   race: [(name, template spell, icon, lore line), ...]     actives first
#
# Active templates: 20549 War Stomp, 26297 Berserking, 20594 Stoneform, 58984 Shadowmeld, 20589 Escape Artist,
#   33697 Blood Fury, 28730 Arcane Torrent, 28880 Gift of the Naaru, 7744 Will of the Forsaken, 59752 Every Man for
#   Himself, 20577 Cannibalize, 2481 Find Treasure, 20600 Perception
# Passive templates: 20573 Hardiness, 20550 Endurance, 20591 Expansive Mind, 20598 The Human Spirit, 20555
#   Regeneration, 6562 Heroic Presence, 20582 Quickness, 20551/20579/20592/20596 Nature/Shadow/Arcane/Frost
#   Resistance, 822 Magic Resistance, 58985 Perception (stealth detection), 20574 Axe and Fist Weapons Spec.,
#   20864 Mace Spec., 20597 Sword Spec., 26290 Bow Spec., 20595 Gun Spec., 20558 Throwing Spec., 20557 Beast Slaying,
#   20576 Command, 20599 Diplomacy, 20593 Engineering Spec., 28875 Gemcutting, 28877 Arcane Affinity, 20552
#   Cultivation, 58943 Da Voodoo Shuffle, 21009 Elusiveness, 5227 Underwater Breathing
RACIALS = {
    # --- 2 actives + 2 passives -----------------------------------------------------------------------------------
    12: [('Embrace of the Loa', 28880, 'ability_racial_embracetheloa', 'The Zandalari call on their loa, as every Witch Doctor of the empire learns to.'),
         ('Pterrordax Swoop', 20589, 'ability_racial_pterrordaxswoop', 'A pterrordax carries the Zandalari out of any snare.'),
         ('City of Gold', 20555, 'ability_racial_cityofgold', 'The riches of Zuldazar heal what the jungle breaks.'),
         ('Da Voodoo Shuffle', 58943, 'ability_racial_wardoftheloa', 'Troll feet never stay rooted for long.')],
    13: [('Darkflight', 20589, 'ability_worgen_darkflight', 'The worgen curse frees those who embrace the beast, as Rangers and Reapers know.'),
         ('Two Forms', 7744, 'ability_racial_twoforms', 'Between the man and the beast, fear finds no hold.'),
         ('Viciousness', 6562, 'ability_racial_viciousness', 'Gilneas hunts with the instincts of the wolf.'),
         ('Aberration', 20551, 'ability_racial_runningwild', 'The curse hardens body and blood.')],
    14: [('Quel\'dorei Torrent', 28730, 'ability_racial_arcaneaffinity', 'The High Elves still draw on the Sunwell\'s legacy, the first lesson of every Starcaller.'),
         ('Farstrider\'s Step', 20589, 'ability_hunter_pet_raptor', 'Rangers of Quel\'Thalas never stay pinned.'),
         ('Arcane Acuity', 20591, 'ability_racial_cantrips', 'Silvermoon\'s exiles keep their sharp minds.'),
         ('Magic Resistance', 20592, 'ability_racial_magicalresistance', 'Elven blood turns aside the arcane.')],
    21: [('Tidal Surge', 20589, 'spell_frost_summonwaterelemental', 'The Naga slip from any hold like the tide.'),
         ('Siren Song', 28730, 'achievement_boss_elitenagamale', 'Azshara\'s children silence their foes with a song of the deep.'),
         ('Serpent Scales', 20551, 'ability_racial_childofthesea', 'Hardened scales from the depths of Nazjatar.'),
         ('Gills', 5227, 'spell_frost_summonwaterelemental', 'Born under the waves.')],
    22: [('Shattered Light', 28880, 'spell_holy_holyprotection', 'The Broken still hold a spark of the Naaru\'s light, as their Sun Clerics remember.'),
         ('Exile\'s Will', 7744, 'spell_shadow_antishadow', 'The fel broke their bodies, not their minds.'),
         ('Exile\'s Resolve', 20579, 'ability_racial_holyresistance', 'What is left of them resists the dark.'),
         ('Shamanic Bond', 20598, 'spell_nature_bloodlust', 'The Broken kept the old shamanic ways alive.')],
    26: [('Bone Shield', 7744, 'ability_racial_skeletonpinkie', 'No mind left to frighten, as every Necromancer intends.'),
         ('Bone Pile', 58984, 'spell_shadow_raisedead', 'A skeleton lying still is just another pile of bones.'),
         ('Unliving', 20579, 'spell_shadow_antishadow', 'Death holds no more terror.'),
         ('No Lungs', 5227, 'spell_shadow_raisedead', 'Bones have nothing to drown.')],
    30: [('Mrgglrrgl!', 20589, 'inv_misc_head_murloc_01', 'Nothing holds a slippery murloc for long.'),
         ('Murloc Swarm', 26297, 'achievement_reputation_murlocoracle', 'Where there is one murloc, there are ten.'),
         ('Amphibious', 20582, 'ability_racial_childofthesea', 'Quick and hard to catch.'),
         ('Born in the Shallows', 5227, 'inv_misc_head_murloc_01', 'The sea is home.')],
    51: [('Gnomish Defiance', 7744, 'spell_shadow_raisedead', 'Death did not dull a gnome\'s stubborn mind, the first rule of any undead Tinker.'),
         ('Cannibalize', 20577, 'ability_racial_cannibalize', 'Undeath has its appetites.'),
         ('Necrotic Intellect', 20591, 'ability_racial_betterlivingthroughchemistry', 'Brilliance outlives the body.'),
         ('Undead Engineering', 20593, 'inv_misc_head_clockworkgnome_01', 'A gnome tinkers even after death.')],
    54: [('Wing Buffet', 20549, 'inv_misc_head_dragon_bronze', 'Dracthyr scatter their foes with a beat of their wings, as their Chronomancers favor.'),
         ('Soar', 20589, 'inv_misc_head_dragon_01', 'No snare holds a dragon.'),
         ('Draconic Mind', 20591, 'inv_misc_head_dragon_black', 'The aspects\' knowledge runs in their blood.'),
         ('Scales of the Aspects', 822, 'inv_misc_head_dragon_blue', 'Dragon scales turn aside magic.')],
    55: [('Fel Torrent', 28730, 'achievement_boss_argus_maleeredar', 'The Eredar unleash a torrent of fel, the gift every Felsworn craves.'),
         ('Sargeras\' Gift', 33697, 'spell_shadow_demonform', 'The Burning Legion empowers its chosen.'),
         ('Man\'ari Mind', 20591, 'spell_shadow_demonicpact', 'Ancient Argus minds, sharp as ever.'),
         ('Demonic Hide', 20579, 'ability_racial_demonbane', 'The fel runs deep.')],
    56: [('Wing Gust', 20589, 'inv_feather_04', 'Harpies take to the air to escape any snare.'),
         ('Screech', 20549, 'ability_hunter_pet_raptor', 'A harpy\'s shriek leaves foes reeling.'),
         ('Swift Talons', 20582, 'ability_hunter_pet_raptor', 'Hard to catch, quick to strike.'),
         ('Keen Eyes', 58985, 'inv_feather_04', 'Nothing hides from a harpy circling above.')],
    57: [('Rocket Jump', 20589, 'ability_racial_rocketjump', 'Every goblin carries a rocket for emergencies, a Tinker\'s favorite.'),
         ('Rocket Barrage', 26297, 'ability_racial_rocketbarrage', 'When in doubt, fire everything.'),
         ('Time is Money', 6562, 'ability_racial_timeismoney', 'A goblin never wastes a swing.'),
         ('Best Deals Anywhere', 20599, 'ability_racial_bestdealsanywhere', 'Every faction is a customer.')],
    59: [('Spatial Rift', 58984, 'ability_racial_spatialrift', 'Void Elves slip between the shadows, as their Cultists learned from the Void.'),
         ('Void Torrent', 28730, 'ability_racial_chillofnight', 'The Void silences those who stare into it.'),
         ('Entropic Embrace', 20579, 'ability_racial_entropicembrace', 'The Void protects its own.'),
         ('Ethereal Connection', 20591, 'ability_racial_etherealconnection', 'Whispers from beyond sharpen the mind.')],
    60: [('Spectral Sight', 20600, 'ability_demonhunter_spectralsight', 'Illidari eyes see what hides.'),
         ('Fel Rush', 20589, 'ability_demonhunter_illidansgrasp', 'The Illidari dash through any trap.'),
         ('Demon Hunter\'s Resolve', 20573, 'ability_racial_demonbane', 'Trained by Illidan to endure.'),
         ('Felblood', 20579, 'spell_shadow_demonform', 'The fel they consumed protects them.')],
    61: [('Mana Break', 28730, 'achievement_boss_illidan', 'The Illidari tear the magic from their foes.'),
         ('Illidari Shadows', 58984, 'ability_racial_shadowmeld', 'Hunters of the night, like their kaldorei kin.'),
         ('Demonbane', 20579, 'ability_racial_demonbane', 'Sworn enemies of the Legion.'),
         ('Demonic Senses', 58985, 'ability_demonhunter_spectralsight', 'No demon hides from them.')],
    63: [('Arcane Pulse', 28730, 'ability_mage_arcanebarrage_nightborne', 'The Nightborne master the arcane of Suramar, a Starcaller\'s dream.'),
         ('Cantrips', 58984, 'ability_racial_cantrips', 'A Nightborne illusion hides them in plain sight.'),
         ('Ancient History', 20591, 'achievement_alliedrace_nightborne', 'Ten thousand years of study.'),
         ('Magical Affinity', 822, 'ability_racial_magicalresistance', 'The Nightwell flows in their veins.')],
    67: [('Combat Analysis', 26297, 'ability_racial_combatanalysis', 'Mechagnome processors read the fight, a Tinker\'s dream.'),
         ('Emergency Failsafe', 59752, 'ability_racial_rearm', 'Built-in protocols reboot a stunned mechagnome.'),
         ('Re-Origination', 20582, 'ability_racial_hyperorganiclightoriginator', 'Optimized servos react faster.'),
         ('Mechanical Mastery', 20593, 'ability_racial_massproduction', 'Built by engineers, for engineers.')],
    70: [('Rootkin Mending', 28880, 'spell_nature_healingtouch', 'The Haranir draw life from the roots of the world, as their Primalists do.'),
         ('Root Step', 20589, 'spell_nature_stoneclawtotem', 'Roots part to let them through.'),
         ('Barkskin Hide', 20551, 'spell_nature_stoneclawtotem', 'Bark and leaf protect them.'),
         ('Gift of the Roots', 20552, 'spell_nature_healingtouch', 'Every herb answers a Haranir.')],
    74: [('Bag of Tricks', 20589, 'ability_racial_makecamp', 'A Vulpera always has something in the bag.'),
         ('Make Camp', 20577, 'ability_racial_returntocamp', 'A short rest at camp mends any wound.'),
         ('Nose for Trouble', 20582, 'ability_racial_returntocamp', 'Desert scavengers dodge danger.'),
         ('Desert Hardened', 20551, 'ability_racial_makecamp', 'The sands of Vol\'dun forge tough hides.')],
    # --- 1 active + 3 passives ------------------------------------------------------------------------------------
    15: [('Harpoon Charge', 20549, 'inv_misc_head_tuskarr', 'Tuskarr hunters bring down their prey in one charge.'),
         ('Rime of the Ancient Mariner', 20596, 'ability_racial_rimeoftheancientmariner', 'Born on the frozen shores of Northrend.'),
         ('Fisherman\'s Patience', 20598, 'inv_misc_head_tuskarr', 'A tuskarr can wait all day for the catch.'),
         ('Harpooner', 20558, 'inv_misc_head_tuskarr', 'Thrown spears never miss their mark.')],
    16: [('Haymaker', 20549, 'ability_racial_haymaker', 'Kul Tiran sailors settle things with their fists, a habit Barbarians admire.'),
         ('Brush It Off', 20550, 'ability_racial_brushitoff', 'A Kul Tiran shrugs off what would drop anyone else.'),
         ('Child of the Sea', 5227, 'ability_racial_childofthesea', 'Raised on the waves of Boralus.'),
         ('Rime of the Ancient Mariner', 20596, 'ability_racial_rimeoftheancientmariner', 'Cold salt spray never bothers them.')],
    17: [('Thunderhoof', 20549, 'ability_racial_bullrush', 'The Taunka shake the tundra like their southern cousins.'),
         ('Hardened by Northrend', 20596, 'spell_frost_frostward', 'Generations of ice and wind.'),
         ('Taunka Endurance', 20550, 'ability_racial_bullrush', 'Built to survive the Borean winter.'),
         ('Hunter of the Tundra', 20557, 'ability_hunter_pet_bear', 'The beasts of Northrend are their prey.')],
    18: [('Fury of the Val\'kyr', 33697, 'inv_misc_head_vrykul', 'The Vrykul fight with the rage of their titan forebears, as their Barbarians do.'),
         ('Titan Blood', 20550, 'ability_racial_avatar', 'Giants among men.'),
         ('Born in the Cold', 20596, 'spell_frost_frostward', 'Northrend is their home.'),
         ('Axe of the Fjord', 20574, 'inv_misc_head_vrykul', 'Every Vrykul grows up with an axe.')],
    20: [('Quaking Palm', 20549, 'ability_monk_paralysis', 'Pandaren masters strike the nerve points, as their monks have for ages.'),
         ('Inner Peace', 20598, '_monkspecialattack_dodgepandaren', 'A calm spirit recovers faster.'),
         ('Bouncy', 20582, '_monkspecialattack_dodgepandaren', 'A pandaren rolls with the blows.'),
         ('Gourmand', 20550, '_pandaren_01', 'A full belly is a strong body.')],
    23: [('Fel Rage', 33697, 'spell_shadow_demonform', 'Fel blood burns in their veins, a fire every Felsworn knows.'),
         ('Demonic Endurance', 20573, 'spell_shadow_ritualofsacrifice', 'Fel-forged bodies shrug off blows that stun others.'),
         ('Fel-Hardened', 20579, 'ability_racial_demonbane', 'The fel already took what it could.'),
         ('Axe of the Horde', 20574, 'achievement_boss_hellfire_felorccouncil', 'The Fel Horde fights with axes.')],
    24: [('Headhunter\'s Frenzy', 26297, 'ability_racial_bloodrage', 'The Amani fight in a blood frenzy.'),
         ('Jungle Stalker', 20582, 'ability_racial_shadowmeld', 'Forest Trolls vanish among the trees.'),
         ('Troll Regeneration', 20555, 'ability_racial_wardoftheloa', 'Troll flesh mends itself.'),
         ('Headhunter', 20558, 'inv_misc_head_troll_01', 'An Amani axe thrown never misses.')],
    25: [('Frostmane Frenzy', 26297, 'spell_frost_frostward', 'The trolls of the frozen north fight hot-blooded.'),
         ('Winter\'s Blood', 20596, 'ability_racial_rimeoftheancientmariner', 'Born in the snows of Zul\'Drak.'),
         ('Troll Regeneration', 20555, 'ability_racial_wardoftheloafrost', 'Troll flesh mends itself.'),
         ('Ice Hunter', 20557, 'inv_misc_head_troll_01', 'The beasts of the north are their prey.')],
    28: [('Blood of the Gods', 26297, 'ability_racial_bloodrage', 'The Drakkari drink the blood of their gods, a rite their Witch Doctors kept.'),
         ('Drakkari Regeneration', 20555, 'ability_racial_wardoftheloa', 'Troll flesh mends itself.'),
         ('Frozen Empire', 20596, 'ability_racial_wardoftheloafrost', 'Zul\'Drak never thaws.'),
         ('Da Voodoo Shuffle', 58943, 'inv_misc_head_troll_01', 'Troll feet never stay rooted for long.')],
    32: [('Survivor\'s Will', 59752, 'achievement_character_human_male', 'Lean, hungry and hard to keep down.'),
         ('Light Step', 20582, 'ability_rogue_sprint', 'A thin frame dodges blows.'),
         ('Human Spirit', 20598, 'achievement_character_human_male', 'The resolve of Stormwind\'s streets.'),
         ('Diplomacy', 20599, 'ability_racial_jackofalltrades', 'A friendly face everywhere.')],
    47: [('Pack Howl', 33697, 'ability_racial_runningwild', 'The alpha leads the pack into battle.'),
         ('Alpha Instinct', 58985, 'ability_racial_twoforms', 'Nothing escapes the alpha\'s senses.'),
         ('Viciousness', 6562, 'ability_racial_viciousness', 'An alpha never misses its prey.'),
         ('Thick Pelt', 20551, 'ability_worgen_darkflight', 'The wild hardened them.')],
    48: [('Fireblood', 20594, 'ability_racial_fireblood', 'The Dark Iron burn away what ails them, as their Pyromancers taught.'),
         ('Forged in Flames', 20573, 'ability_racial_foregedinflames', 'Shadowforge steel and stubborn skulls.'),
         ('Mole Machine', 20593, 'ability_racial_dungeondelver', 'Dark Iron engineering is the finest under the mountain.'),
         ('Mace of the Forge', 20864, 'ability_racial_mastercraft', 'The hammer is a Dark Iron\'s first tool.')],
    49: [('Ancestral Call', 33697, 'ability_racial_ancestralcall', 'The Mag\'har call on the spirits of Draenor, as their Primalists do.'),
         ('Open Skies', 6562, 'ability_racial_openskies', 'Untainted by the fel, their strikes fly true.'),
         ('Savage Blood', 20573, 'ability_racial_pureblood', 'Pure orcish blood shrugs off a stun.'),
         ('Command', 20576, 'achievement_alliedrace_magharorc', 'Wolves and beasts follow the Mag\'har.')],
    50: [('Ursine Fury', 26297, 'ability_racial_bearform', 'The Furbolg fight with the strength of the bear.'),
         ('Thick Fur', 20551, 'inv_cape_special_furbolg_d_01', 'Children of the wild, at home in nature.'),
         ('Furbolg Endurance', 20550, 'ability_racial_bearform', 'Big, and hard to bring down.'),
         ('Gift of the Grove', 20552, 'inv_cape_special_furbolg_d_01', 'The forests of Ashenvale share their herbs.')],
    53: [('Ogre Slam', 20549, 'achievement_boss_gruul', 'One slam is usually enough, as every ogre Barbarian knows.'),
         ('Two Heads Are Better', 20550, 'achievement_boss_gruulthedragonkiller', 'Ogres are built to last.'),
         ('Thick Skull', 20573, 'achievement_boss_gruul', 'Hard to stun a head that thick.'),
         ('Club Mastery', 20864, 'achievement_reputation_ogre', 'Big club, big hit.')],
    62: [('Light\'s Reckoning', 28880, 'ability_racial_finalverdict', 'The Lightforged carry the Naaru\'s light, as their Templars and Sun Clerics do.'),
         ('Forge of Light', 20598, 'ability_racial_forgeoflight', 'The Light renews them.'),
         ('Holy Resistance', 822, 'ability_racial_holyresistance', 'The Light shields its chosen.'),
         ('Lightforged Resolve', 20573, 'ability_racial_forceshield', 'Forged in Light, they stand firm.')],
    66: [('Bull Rush', 20549, 'ability_racial_bullrush', 'Highmountain charge like the great moose.'),
         ('Mountaineer', 20550, 'ability_racial_mountaineer', 'Raised on the peaks of Highmountain.'),
         ('Pride of Ironhorn', 20573, 'ability_racial_prideofironhorn', 'Hard as the mountain.'),
         ('Rugged Tenacity', 20551, 'achievements_zone_highmountain', 'The wilds of Highmountain toughen them.')],
    68: [('Azerite Surge', 20594, 'ability_earthenfury_giftofearth', 'The Earthen are made of living stone, as their Runemasters remember.'),
         ('Titan-Forged', 20573, 'ability_earthen_pillar', 'Stone does not stagger.'),
         ('Stoneskin', 20550, 'ability_earthenfury_giftofearth', 'Living rock is hard to break.'),
         ('Gemcutting', 28875, 'ability_earthen_pillar', 'The Earthen know every gem of the deep.')],
}
# both factions of the same people share their racials
for twin, base in ((29, 20), (31, 30), (58, 54), (69, 68), (71, 70)):
    RACIALS[twin] = RACIALS[base]

ACTIVE_TEMPLATES = {20549, 26297, 20594, 58984, 20589, 33697, 28730, 28880, 7744, 59752, 20577, 2481, 20600}
SPELL_BASE = 14000000          # new spell ids: SPELL_BASE + race * 10 + 1..4


def spell_ids(race):
    return [SPELL_BASE + race * 10 + k for k in range(1, 5)]
